// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9s4kZg6QaxyVFl34s0zBjYG_UVOSHQZ8',
    appId: '1:622751275346:web:5b59bec2e7dfd6dc53428b',
    messagingSenderId: '622751275346',
    projectId: 'target-c1339',
    authDomain: 'target-c1339.firebaseapp.com',
    storageBucket: 'target-c1339.firebasestorage.app',
    measurementId: 'G-R9QRZRDMWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZt4wsI7TNeB-yr7QgzMxKGxPBBhwZq8w',
    appId: '1:622751275346:android:774112689a82701953428b',
    messagingSenderId: '622751275346',
    projectId: 'target-c1339',
    storageBucket: 'target-c1339.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg7A4_qrqsD2JVQg1fJqcoUUQl21lR1Uc',
    appId: '1:622751275346:ios:58c35e1940bcdeb753428b',
    messagingSenderId: '622751275346',
    projectId: 'target-c1339',
    storageBucket: 'target-c1339.firebasestorage.app',
    iosBundleId: 'com.example.agriStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg7A4_qrqsD2JVQg1fJqcoUUQl21lR1Uc',
    appId: '1:622751275346:ios:58c35e1940bcdeb753428b',
    messagingSenderId: '622751275346',
    projectId: 'target-c1339',
    storageBucket: 'target-c1339.firebasestorage.app',
    iosBundleId: 'com.example.agriStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOzBkjaqA0Dyvdb0Eo0oDHQNpl5j-Bf3s',
    appId: '1:622751275346:web:169f34c6b8b5e7d953428b',
    messagingSenderId: '622751275346',
    projectId: 'target-c1339',
    authDomain: 'target-c1339.firebaseapp.com',
    storageBucket: 'target-c1339.firebasestorage.app',
    measurementId: 'G-90W0MSGG91',
  );
}
